# Site settings
title: Sonic Writing
header-img: img/home-bg.jpg
email: th.list@gmail.com
description: "A research blog for the AHRC funded Sonic Writing research project"
baseurl: ""
url: "http://thormagnusson.github.io/sonicwriting"
twitter_username: thormagnusson
github_username:  thormagnusson
facebook_username:  thorlmagnusson

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
