# Site settings
title: Sonic Writing
copyright: Thor Magnusson
header-img: img/home-bg.jpg
email: th.list@gmail.com
description: "A research blog for the AHRC funded Sonic Writing research project. This project explores how musical instrument design, musical notation techniques, and phonography is translated into current works in digital media."
baseurl: ""
url: "http://thormagnusson.github.io/"
twitter_username: thormagnusson
github_username:  thormagnusson
facebook_username:  thorlmagnusson

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /blog/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
