# Site settings
title: Sonic Writing
copyright: Thor Magnusson
header-img: img/home-bg.jpg
email: th.list@gmail.com
description: "A research blog for the AHRC funded Sonic Writing research project. This project explores how musical instrument design, musical notation techniques, and phonography is translated into current works in digital media."
baseurl: ""
url: "http://www.sonicwriting.org"
twitter_username: thormagnusson
github_username:  thormagnusson
facebook_username:  thorlmagnusson
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
paginate: 25
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
